In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
a = np.ones((3,5))
print(a)
a.dtype

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


dtype('float64')

reshaping array starts
reshape converts the 1d array to ndimensional array

In [3]:
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
reshape= arr.reshape(3,4)
print(reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3darray

In [12]:
reshape2 = arr.reshape(2,3,2)
print(reshape2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
reshape2.ndim

3

flatten and ravel array

flatten converts any dimensional array to 1d array and ravel also do the same but the difference is in ravel when weupdate the orginal files updates but in flatten only the copy updates original doesnt getupdated.. similar like copy and view

In [14]:
reshape3 = reshape2.flatten()
print(reshape3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


transposing array : converts rows into coloumns

In [8]:
arrays = np.arange(1,13).reshape(3,4)
print(arrays)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
arrays.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [10]:
arrays.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

concanate arrays vertically and horizonatally

In [14]:
arr_a = np.arange(12,24).reshape(3,4)
print(arr_a)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [15]:
arr_b = np.arange(12).reshape(3,4)
print(arr_b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
vert_concat = np.vstack((arr_a,arr_b))
print(vert_concat)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
hori_concat = np.hstack((arr_a,arr_b))
print(hori_concat)

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]]


splitting array

In [7]:
split = np.arange(1,17).reshape(4,4)
print(split)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
splitarr = np.split(split,2)
print(splitarr)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [9]:
splitarr[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
np.hsplit(split,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [11]:
np.flipud(split)

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [12]:
np.fliplr(split)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

mathematical calculations

In [13]:
data = [4, 5, 6, 7, 8]
std_dev = np.std(data, ddof=1)  # ddof=1 for sample standard deviation
print(std_dev)  # Output: 1.5811388300841898

1.5811388300841898


In [3]:
print(np.__version__)

1.26.4


In [14]:
print(split.ndim)

2
