In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
arr.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [7]:
#Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [6]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [3]:
a = np.ones((3,5),dtype= int)
print(a)
a.dtype

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


dtype('int32')

reshaping array starts
reshape converts the 1d array to ndimensional array

In [18]:
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
reshape= arr.reshape(3,4)
print(reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3darray

In [20]:
reshape2 = arr.reshape(2,3,2)
print(reshape2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
reshape2.ndim

3

flatten and ravel array

flatten converts any dimensional array to 1d array and ravel also do the same but the difference is in ravel when weupdate the orginal files updates but in flatten only the copy updates original doesnt getupdated.. similar like copy and view

In [22]:
reshape3 = reshape2.flatten()
print(reshape3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


transposing array : converts rows into coloumns

In [23]:
arrays = np.arange(1,13).reshape(3,4)
print(arrays)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
arrays.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [25]:
arrays.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

concanate arrays vertically and horizonatally

In [26]:
arr_a = np.arange(12,24).reshape(3,4)
print(arr_a)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [27]:
arr_b = np.arange(12).reshape(3,4)
print(arr_b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
vert_concat = np.vstack((arr_a,arr_b))
print(vert_concat)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
hori_concat = np.hstack((arr_a,arr_b))
print(hori_concat)

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]]


splitting array

using split function we can use axis function like axis = 1 or 2 but where as in hsplit or v split we cannot use axis

In [30]:
split = np.arange(1,17).reshape(4,4)
print(split)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [31]:
splitarr = np.split(split,2)
print(splitarr)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [32]:
splitarr[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
np.hsplit(split,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

FLIPUD = FLIP UP TO DOWN 

In [34]:
np.flipud(split)

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

FLIP LEFT TO RIGHT

In [35]:
np.fliplr(split)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

* 5TH VIDEO mathematical OPERATIONS

ARTHEMITIC FUNCTIONS = np.add, np.multiply, np.subtract, np.divide, np.floor_divide, np.mod, np.sqrt, np.pow

TRIGNOMETRIC FUNCTIONS = np.sin, np.cos, np.tan 

LOGICAL OPERATORS = np.logical_and(arr1,arr2), np.logical_or(), np.logical_not()

STATSTICAL OPERATIONS = np.nean(), np.std(), np.meadin(), np.prod()

EXPONENTIAL AND LOGARITHMIC FUNCTIONS

In [3]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4])
np.exp(arr1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.log10("")

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [7]:
import numpy as np
array = np.array([12,13,15,30,14,32])
np.mean(array)

19.333333333333332

concatenate 2 NumPy arrays

In [13]:
import numpy as np
a = np.array([1,2])
b = np.array([5,6])
c = np.concatenate((a,b))
print(c)
b.ndim

[1 2 5 6]


1

NUMPY MULTIPLICATION

In [15]:
import numpy as np

# NumPy matrices
A = np.arange(15,24).reshape(3,3)
B = np.arange(20,29).reshape(3,3)
print("A: ",A)
print("B: ",B)

# Multiply A and B
result = A*B
print("Result: ", result)

A:  [[15 16 17]
 [18 19 20]
 [21 22 23]]
B:  [[20 21 22]
 [23 24 25]
 [26 27 28]]
Result:  [[300 336 374]
 [414 456 500]
 [546 594 644]]
